### ISSUE TITLE
OSM request failed. Statuscode: 429

### ISSUE THREAD

**Issue by dephiloper** [LB31/HikingForNerds#126]
When querying for routes sometimes this error occurs.

`I/flutter ( 2792): OSM request failed. Statuscode:429
I/flutter ( 2792):  Query: http://overpass-api.de/api/interpreter?data=[bbox:52.53052794894329, 13.388411315574007, 52.57536004857377, 13.46214495473423][out:json][timeout:300];way["highway"](around:2500.0,52.5529497242998, 13.42529696829996);(._;>;); out body qt;
I/flutter ( 2792):  Message: <?xml version="1.0" encoding="UTF-8"?>
I/flutter ( 2792): <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
I/flutter ( 2792):     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
I/flutter ( 2792): <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
I/flutter ( 2792): <head>
I/flutter ( 2792):   <meta http-equiv="content-type" content="text/html; charset=utf-8" lang="en"/>
I/flutter ( 2792):   <title>OSM3S Response</title>
I/flutter ( 2792): </head>
I/flutter ( 2792): <body>
I/flutter ( 2792): 
I/flutter ( 2792): <p>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</p>
I/flutter ( 2792): <p><strong style="color:#FF0000">Error</strong>: runtime error: open64: 0 Success /osm3s_v0.7.56_osm_base Dispatcher_Client::request_read_and_idx::rate_limited. Please check /api/status for the quota of your IP address. </p>
I/flutter ( 2792): 
I/flutter ( 2792): </body>
I/flutter ( 2792): </html>
E/flutter ( 2792): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter ( 2792): <?xml version="1.0" encoding="UTF-8"?>
E/flutter ( 2792): ^
E/flutter ( 2792): 
E/flutter ( 2792): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1394:5)
E/flutter ( 2792): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1261:9)
E/flutter ( 2792): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:926:22)
E/flutter ( 2792): #3      _parseJson (dart:convert-patch/convert_patch.dart:31:10)
E/flutter ( 2792): #4      JsonDecoder.convert (dart:convert/json.dart:495:36)
E/flutter ( 2792): #5      OsmData._importJsonNodesAndWays (package:hiking4nerds/services/routing/osmdata.dart:342:38)
E/flutter ( 2792): #6      OsmData.calculateHikingRoutes (package:hiking4nerds/services/routing/osmdata.dart:157:5)
E/flutter ( 2792): <asynchronous suspension>
E/flutter ( 2792): #7      _RouteListState.calculateRoutes (package:hiking4nerds/pages/setup/route_list.dart:32:32)
E/flutter ( 2792): #8      _RouteListState.initState (package:hiking4nerds/pages/setup/route_list.dart:25:5)
E/flutter ( 2792): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4456:58)
E/flutter ( 2792): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4302:5)
E/flutter ( 2792): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
E/flutter ( 2792): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
E/flutter ( 2792): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5570:14)
E/flutter ( 2792): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
E/flutter ( 2792): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
E/flutter ( 2792): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
E/flutter ( 2792): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
E/flutter ( 2792): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4307:5)
E/flutter ( 2792): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4302:5)
E/flutter ( 2792): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
E/flutter ( 2792): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
E/flutter ( 2792): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5570:14)
E/flutter ( 2792): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
E/flutter ( 2792): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
E/flutter ( 2792): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5570:14)
E/flutter ( 2792): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
E/flutter ( 2792): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
E/flutter ( 2792): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
E/flutter ( 2792): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
E/flutter ( 2792): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4307:5)
E/flutter ( 2792): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4482:11)
E/flutter ( 2792): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4302:5)
E/flutter ( 2792): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
E/flutter ( 2792): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
E/flutter ( 2792): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5570:14)
E/flutter ( 2792): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
E/flutter ( 2792): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
E/flutter ( 2792): #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5570:14)
E/flutter ( 2792): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
E/flutter ( 2792): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
E/flutter ( 2792): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
E/flutter ( 2792): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
E/flutter ( 2792): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4307:5)
E/flutter ( 2792): #44     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4482:11)
E/flutter ( 2792): #45     ComponentElemen
I/flutter ( 2792): ## 10 routes found
`

**Comment by dephiloper** [comment]
since we changed the server to one without rate limit this does not occur anymore
